### ISSUE TITLE
CL_INVALID_BUILD_OPTIONS

### ISSUE THREAD

**Issue by radoye** [acowley/CLUtil#3]
Any hints here (if you're still maintaining this code)? I'm getting this on both NVIDIA and Intel OpenCL implementations on two different machines (Arch linux on both though). Happens with the Hackage OpenCL as well as [your OpenCL fork](https://github.com/acowley/opencl) (the fork compiles cleanly and examples work on both systems). All attempts were with `lts-7.14` (GHC 8.0.1) and `main = test1`. It seems to fail in `kernelFromFile`.
``` shell
rrs@hummingbird> stack ghc -- -o ./examples/demo ./examples/TestEZ.hs                       ~/workspace/dev/haskell/lab/CLUtil
[1 of 1] Compiling Main             ( examples/TestEZ.hs, examples/TestEZ.o )
Linking ./examples/demo ...
rrs@hummingbird> ./examples/demo                                                            ~/workspace/dev/haskell/lab/CLUtil
demo: CL_INVALID_BUILD_OPTIONS
[1] rrs@hummingbird>  
```

**Comment by acowley** [comment]
Can you try changing the build options [here](https://github.com/acowley/CLUtil/blob/master/src/Control/Parallel/CLUtil.hs#L57) to the empty string?

**Comment by radoye** [comment]
Thanks for the quick reply! Yes, that worked.
For completeness, both platforms have OpenCL version 1.2 (Intel & CUDA 8).

**Comment by acowley** [comment]
I'm sorry about the issue. It was some naive optimism on my part that the system OpenCL compiler might use the lack of aliasing to some benefit. That it's no longer supported is telling!
