### ISSUE TITLE
loadProgramWOptions does not expose compile errors

### ISSUE THREAD

**Issue by bergey** [acowley/CLUtil#7]
`loadProgramWOptions` raises an exception on compile failure, but there isn't enough information in the exception to call `clGetProgramBuildLog` (just `CL_BUILD_PROGRAM_FAILURE`).  It would be nice to print the build log, or return the program `p` in the exception, or something, to make this easier to handle.  I have one quick-and-dirty approach at https://github.com/bergey/CLUtil/commit/8986f72fd1f4cd9b39563b2fb56bc6d8363517a3

**Comment by acowley** [comment]
Your quick and dirty fix looks like more or less the right thing. Is it worth doing anything more complicated?
